### ISSUE TITLE
Won't work when several circuit connected entities share the same position.

### ISSUE THREAD

**Issue by lossycrypt** [shanemadden/factorio-power-grid-comb#1]
From looking at the code you recreate the circuit connections based soley on position. This will not work if a mod adds circuit-connectable entities that have exactly the same position. Miniloader might be such a case, though i don't know its exact external structure. The correct way to handle this would probably to do it like blueprints, i.e. by using the table index to determine what entities to connect to.

**Comment by shanemadden** [comment]
Oh, tricky. I switched to find_entity() to get the connection target since the target could be a power pole that just got destroyed and re-created, so the existing references to that entity were no good - but for cases where it's connecting to anything other than a just-recreated-pole (like a miniloader), there's no reason not to just use the old target_entity.  I'll switch that up, thanks!

**Comment by lossycrypt** [comment]
Even for power poles it's not always correct, i.e. when two power poles are at the same position. Not sure if there are any mods out there that currently do that, but i once had a compressed-circuit concept mod that used that sort of behavior. The way blueprints handle it is they just use the table index. So if the pole at index 1 was connected to the one at index 5 before recreation it will be connected to that again. Of course that means you have to first identify which pole is which in the list, but that should be trivial with unit_number.

**Comment by shanemadden** [comment]
Pushed a fix up in 0.16.1 that solves for every case except stacked power poles, but I follow - I just need to track references of which new pole replaces each destroyed entity.  I think I know what needs to happen..

**Comment by shanemadden** [comment]
I think this should do it - no more find_entity at all, just tracking replacements based on unit number. https://github.com/shanemadden/factorio-power-grid-comb/commit/40ad9c59880823fc76c8fbf36c64dba48c60d054

Thanks for the help!
