### ISSUE TITLE
Bad visibility of icon in inventory

### ISSUE THREAD

**Issue by ST-DDT** [shanemadden/factorio-power-grid-comb#3]
Due to the icon being mostly grey it is sometimes hard to spot inside the inventory.

![grafik](https://user-images.githubusercontent.com/1579362/39542288-70a90cb8-4e48-11e8-9ca4-3f0ed33e2053.png)

Would you consider adding a blue or green or yellow (or whatever colored) background to the icon?

![grafik](https://user-images.githubusercontent.com/1579362/39542423-d40c56fc-4e48-11e8-836e-9c9eb7cf7601.png)

**Comment by shanemadden** [comment]
I like that idea, maybe a yellow tint to the background to indicate that it's power-related.

**Comment by shanemadden** [comment]
Added a new yellow tinted blueprint background in 0.16.3, should be a lot more visible now!
